apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::914642237124:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-78RB7UAC2ZX2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::914642237124:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-28T16:15:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1566"
  uid: 50fd4e47-97cc-4a9d-b2b7-08d21a2531c1
